### ISSUE TITLE
XDA details link in the repo 

### ISSUE THREAD

**Issue by jsroyal** [xda/summer-of-code#5]
There is no link in this repo to know more about XDA.
So my Idea is about if newbie/newcomers come here on the purpose of GSOC then they should to know about XDA.
Need also brief context about it and provide a link about.

**Comment by jerdog** [comment]
There is a bit for info about the GSoC (https://github.com/xda/summer-of-code#what-is-google-summer-of-code) but that's good info to add bits about who XDA is. Will add that

**Comment by jsroyal** [comment]
@jerdog Thanks for taking as input.
