### ISSUE TITLE
Existing Idea list about XDA

### ISSUE THREAD

**Issue by jsroyal** [xda/summer-of-code#6]
Do we have existing list of ideas about XDA to contribute them directly instead of having new ideas.
ALso there is line 
#Student looking Ideas 

> Look through the [Ideas](https://github.com/xda/summer-of-code/blob/master/IDEAS_template.md) list to find one that strikes your fancy, or add your own to the list and then create your proposal.
 
But there is template of pitch.
Yeah! In the wiki we do 3-4  proposed list.Also need to add the list on about link.

**Comment by jerdog** [comment]
Yes - there is a place for existing ideas and the template for submitting an idea

**Comment by jsroyal** [comment]
@jerdog Please update the link to mention above issue > Look through the Ideas list to find one that strikes your fancy, or add your own to the list and then create your proposal.
Instead of this give this [link](https://github.com/xda/summer-of-code/wiki/Ideas#submitted-ideas).
Do you see the linking issue here!
Or Can make PR for that if you agree?
